# Copyright (c) 2026 Forschungszentrum Juelich GmbH, Juelich Supercomputing Centre
# Contributors:
# - Aravind Sankaran
# SPDX-License-Identifier: BSD-3-Clause

"""
Flask blueprint exposing pigeon-server upload API endpoints.

Endpoints:
    POST /generate-upload-url
    POST /upload/<token>
"""

from flask import Blueprint, request, jsonify, url_for
import logging
import os

from .request_manager import RequestManager

logger = logging.getLogger(__name__)



token_key = os.getenv("PIGEON_TOKEN_KEY")
if token_key is None:
    raise RuntimeError("PIGEON_TOKEN_KEY environment variable must be set")

token_age = int(os.getenv("PIGEON_TOKEN_AGE", "600"))

dispatch_key = os.getenv("PIGEON_DISPATCH_KEY")
if dispatch_key is None:
    raise RuntimeError("PIGEON_DISPATCH_KEY environment variable must be set")

dispatch_url = os.getenv("PIGEON_DISPATCH_URL")
if dispatch_url is None:
    raise RuntimeError("PIGEON_DISPATCH_URL environment variable must be set")

request_manager = RequestManager(dispatch_key, dispatch_url, token_key, token_age)

bp = Blueprint("apis", __name__)


@bp.route("/generate-upload-url", methods=["POST"])
def generate_upload_url():
    """
    Generate a short-lived upload URL for a validated object key.

    **Request JSON**::

        {"object_key": "<string>"}

    :returns: JSON response containing an upload URL or an error message.
    :rtype: flask.Response

    Successful response body::

        {"upload_url": "upload/<token>"}

    Error response bodies::

        {"error": "Missing object_key"}
        {"error": "..."}

    :statuscode 200: Upload URL created.
    :statuscode 400: Missing or invalid ``object_key``.
    :statuscode 500: Internal error while generating URL.
    """
    data = request.get_json(silent=True) or {}
    object_key = data.get("object_key")

    if not object_key:
        logger.warning(f"Missing object_key in request")
        return jsonify({"error": "Missing object_key"}), 400

    try:
        token = request_manager.generate_upload_token(object_key)
        # Return relative upload path so the client can compose it with
        # the user-provided server base URL (scheme/host aware).
        url = f"upload/{token}"
        return jsonify({"upload_url": url}), 200
    except Exception as e:
        return _process_exception(e)

@bp.route("/upload/<token>", methods=["POST"])
def upload(token):
    """
    Accept and process a binary upload for the provided signed token.

    :param token: Signed upload token generated by ``/generate-upload-url``.
    :type token: str
    :returns: JSON response with success message or error message.
    :rtype: flask.Response

    **Request requirements**

    - Method: ``POST``
    - Content-Type: ``application/octet-stream``
    - Body: raw uploaded bytes (streamed; not fully buffered)

    Successful response body::

        {"message": "File uploaded successfully"}

    Error response bodies::

        {"error": "No data provided"}
        {"error": "Content-Type must be application/octet-stream"}
        {"error": "..."}

    :statuscode 200: Upload processed successfully.
    :statuscode 400: Empty upload body.
    :statuscode 415: Unsupported content type.
    :statuscode 500: Token, dispatch, or processing failure.
    """

    if request.content_type != "application/octet-stream":
        return jsonify({"error": "Content-Type must be application/octet-stream"}), 415

    # If client sends an empty body, content_length may be 0 or None (chunked)
    if request.content_length == 0:
        return jsonify({"error": "No data provided"}), 400

    try:
        request_manager.process_upload_stream(
            token=token,
            stream=request.stream,                 # <-- do not read into memory
            content_length=request.content_length, # may be None if chunked
        )
        return jsonify({"message": "File uploaded successfully"}), 200
    except Exception as e:
        return _process_exception(e)

def _process_exception(e: Exception) -> (str, int):
    if isinstance(e, RuntimeError):
        try:
            error_code = str(e).split(",")[0].strip()
            error_message = ",".join(str(e).split(",")[1:]).strip()
        except Exception as parse_e:
            logger.error(f"Unexpected error: {parse_e}")
            return jsonify({"error": "Internal error"}), 500
        if error_code in ["500",]:
            return jsonify({"error": "Internal error"}), int(error_code)
        else:
            return jsonify({"error": error_message}), int(error_code)
    else:
        logger.error(f"Unexpected error: {e}")
        return jsonify({"error": "Internal error"}), 500